# Generated by Django 5.2.7 on 2026-02-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medialibraryitem',
            name='page_type',
            field=models.IntegerField(choices=[(0, 'Front'), (1, 'Middle'), (2, 'Back')], default=1),
        ),
    ]
