# Generated by Django 5.2.7 on 2025-12-17 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medialibraryitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='medialibrary',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_libraries_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medialibrary',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medialibrary',
            name='studio_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
