# Generated by Django 5.2.7 on 2025-12-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_medialibraryitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'customer'), (1, 'operation'), (2, 'lab'), (3, 'admin'), (4, 'super admin')], default=0),
        ),
    ]
