# Generated by Django 5.2.7 on 2026-02-03 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_medialibraryitem_page_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialLinks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('social_media_platform', models.CharField(max_length=20)),
                ('social_media_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Social Links',
                'db_table': 'user_social_links',
            },
        ),
    ]
