# Generated by Django 5.2.7 on 2025-12-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='studio_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
