# Generated by Django 5.2.7 on 2026-02-03 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_usersociallinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersociallinks',
            name='remaing_credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersociallinks',
            name='used_credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersociallinks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_social_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
