# Generated by Django 5.2.7 on 2026-02-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_usersociallinks_remaing_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersociallinks',
            name='remaing_credit',
        ),
        migrations.RemoveField(
            model_name='usersociallinks',
            name='used_credit',
        ),
        migrations.AddField(
            model_name='user',
            name='remaing_credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='used_credit',
            field=models.IntegerField(default=0),
        ),
    ]
