# Generated by Django 5.2.7 on 2025-12-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_studio_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='studio_name',
            new_name='organization_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'customer'), (1, 'studio'), (2, 'lab'), (3, 'admin'), (4, 'super admin')], default=0),
        ),
    ]
