# Generated by Django 5.2.7 on 2026-02-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_usersociallinks_remaing_credit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='remaing_credit',
            new_name='remaining_credit',
        ),
    ]
