# Generated by Django 5.2.7 on 2026-02-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_remaing_credit_user_remaining_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='medialibrary',
            name='instagram_profile_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medialibrary',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
