# Generated by Django 5.2.7 on 2025-12-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_user_gender_alter_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpaymenttransaction',
            name='transaction_date',
        ),
        migrations.AddField(
            model_name='userpaymenttransaction',
            name='operation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpaymenttransaction',
            name='transaction_active_from_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
