# Generated by Django 5.2.5 on 2025-08-31 19:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "role",
                    models.CharField(
                        choices=[(0, "customer"), (1, "admin"), (3, "super admin"), (2, "operation")],
                        default=None,
                        max_length=50,
                    ),
                ),
                ("profile_picture", models.CharField(max_length=128, null=True)),
                (
                    "gender",
                    models.CharField(choices=[(0, "male"), (1, "female"), (2, "other")], max_length=50, null=True),
                ),
                ("date_of_birth", models.DateField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("phone", models.CharField(max_length=20)),
                ("first_address", models.CharField(max_length=128, null=True)),
                ("second_address", models.CharField(max_length=128, null=True)),
                ("city", models.CharField(max_length=50, null=True)),
                ("state", models.CharField(max_length=50, null=True)),
                ("zip_code", models.CharField(max_length=10, null=True)),
                ("country", models.CharField(max_length=50, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="base.user")),
            ],
            options={
                "db_table": "user_addresses",
                "unique_together": {("user", "is_primary")},
            },
        ),
    ]
