# Generated by Django 5.2.7 on 2025-10-04 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaLibrary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media_type', models.IntegerField(choices=[(0, 'Image'), (1, 'Video'), (2, 'Flipbook')], max_length=20)),
                ('media_title', models.CharField(blank=True, max_length=200, null=True)),
                ('media_description', models.TextField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Media Libraries',
                'db_table': 'media_libraries',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'customer'), (1, 'admin'), (3, 'super admin'), (2, 'operation')], default=None, max_length=50),
        ),
        migrations.CreateModel(
            name='MediaLibraryItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media_url', models.URLField(max_length=500)),
                ('media_item_title', models.CharField(blank=True, max_length=200, null=True)),
                ('media_item_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('media_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_library_items', to='base.medialibrary')),
            ],
            options={
                'db_table': 'media_library_items',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserFunctions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('function_start_date', models.DateField(blank=True, null=True)),
                ('function_end_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'approved'), (2, 'rejected')], default=0, max_length=20)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_functionalities', to='base.user')),
            ],
            options={
                'verbose_name_plural': 'User Functionalities',
                'db_table': 'user_functionalities',
            },
        ),
        migrations.AddField(
            model_name='medialibrary',
            name='user_functionality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_libraries', to='base.userfunctions'),
        ),
    ]
