# Generated by Django 5.2.7 on 2025-10-04 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_medialibrary_alter_user_role_medialibraryitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medialibrary',
            name='media_type',
            field=models.IntegerField(choices=[(0, 'Image'), (1, 'Video'), (2, 'Flipbook')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'customer'), (1, 'admin'), (3, 'super admin'), (2, 'operation')], default=None),
        ),
        migrations.CreateModel(
            name='UserEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('function_start_date', models.DateField(blank=True, null=True)),
                ('function_end_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'approved'), (2, 'rejected')], default=0)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_functionalities', to='base.user')),
            ],
            options={
                'verbose_name_plural': 'User Functionalities',
                'db_table': 'user_events',
            },
        ),
        migrations.AlterField(
            model_name='medialibrary',
            name='user_functionality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_libraries', to='base.userevents'),
        ),
        migrations.DeleteModel(
            name='UserFunctions',
        ),
    ]
