# Generated by Django 5.2.7 on 2025-10-05 07:27

from django.db import migrations, models


def populate_username(apps, schema_editor):
    User = apps.get_model("base", "User")
    for user in User.objects.all():
        if not user.username:
            user.username = user.email
            user.save()


def reverse_populate_username(apps, schema_editor):
    User = apps.get_model("base", "User")
    for user in User.objects.all():
        user.username = ""
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_medialibrary_media_type_alter_user_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
        migrations.RunPython(populate_username, reverse_populate_username),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(unique=True),
        ),
    ]
