# Generated by Django 5.2.7 on 2025-10-05 07:31

from django.db import migrations, models
from django.utils import timezone


def populate_date_joined(apps, schema_editor):
    User = apps.get_model("base", "User")
    for user in User.objects.all():
        if not hasattr(user, "date_joined") or user.date_joined is None:
            user.date_joined = user.created_at or timezone.now()
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_auto_20251005_0729"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.RunPython(populate_date_joined, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
