# Generated by Django 5.2.7 on 2025-10-05 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medialibrary',
            name='user_functionality',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_libraries', to='base.userevents'),
        ),
    ]
