# Generated by Django 5.2.7 on 2025-10-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_medialibrary_user_functionality'),
    ]

    operations = [
        migrations.AddField(
            model_name='medialibrary',
            name='media_unique_id',
            field=models.CharField(default='434rtfdde', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
